name: Auto Api Secret

on:
  schedule:
    - cron: '0 0-3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install requirements
        run: pip install requests telepot

      - name: Test Api
        env:
          TELEBOT_TOKEN: ${{ secrets.TELEBOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CONFIG_ID: ${{ secrets.CONFIG_ID }}
          CONFIG_KEY: ${{ secrets.CONFIG_KEY }}
        run: |
          echo "$(date +"%Y-%m-%d %H:%M:%S") begin" > time.log
          python 1.py

      - name: Commit refresh_token
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "ccknbc"
          git add .
          git commit -m "update new refresh_token" || echo "no change"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
